### PR TITLE
fix: resolve #3: avoid coloring the y-labels with plot colors

### LINKED ISSUE #3: y label and y axis gets color at line intercept point
This is a fun little project!  

Currently the Y axis and label that correspond to the leftmost data point of a line get printed with the color of that data point. This is distracting when using `-f` on data sets that are highly variable. This seems non-ideal.

image
image

### PR DESCRIPTION
**Pull request by AdrianDC**
fix: resolve #3: avoid coloring the y-labels with plot colors

 * Test: seq 1 1000 | shuf | plot -c r

fix: resolve #3: use last point for the right side cross print
    
 * Test: seq 1 100 | shuf | plot -c r -y 10:3:3

### CODE REVIEW

**Comment by AdrianDC** [comment]
image

**Comment by holmanb** [comment]
Nice!  That looks much better.

File: src/display.c [hunk 1]
```diff
@@ -139,16 +139,22 @@ plot_print_y_label(struct plot *p, struct canvas_elem e, double l, int side)
...
 	}
 
-	if (side == 1) {
-		printf(p->y_label.l_fmt, l, plot_charsets[p->charset][pp]);
-	}else if (side == 2) {
-		printf(p->y_label.r_fmt, plot_charsets[p->charset][pp], l);
+	printf("%s", plot_charsets[p->charset][pp]);
+
+	if (side == 2) {
+		printf("\033[0m");
```
Comment (annacrombie) [inline src/display.c:156]: this is redundant, line 150 already clears the color

File: src/display.c [hunk 2]
```diff
@@ -139,16 +139,22 @@ plot_print_y_label(struct plot *p, struct canvas_elem e, double l, int side)
 
 	pp = side == 1 ? PPTLeft | ((e.peice & 0x8) >> 2) : PPTRight | e.peice;
 
+	if (side == 1) {
+		printf("\033[0m");
```
Comment (annacrombie) [inline src/display.c:143]: You should only print this out `if (p->color)` so that no escape sequences are generated if no colored output is enabled

File: src/display.c [hunk 3]
```diff
@@ -175,7 +181,7 @@ plot_print_canvas(struct plot *plot)
 		}
 
 		if ((plot->y_label.side & 2) == 2) {
-			plot_print_y_label(plot, plot->canvas[0][y], plot->labels[y], 2);
+			plot_print_y_label(plot, plot->canvas[plot->width - 1][y], plot->labels[y], 2);
```
Comment (annacrombie) [inline src/display.c:184]: nice catch!

**Review by annacrombie — CHANGES_REQUESTED** [review]
other than minor changes, this looks good.  I agree, it looks better!

File: src/display.c (hunk 1 above)
Comment (AdrianDC) [reply src/display.c:156]: I disagree on this one, line 150 does not reset the right side color (as it is a cross).

Test: `seq 1 100 | shuf | ./build/plot -c r -y 10:3:3`

File: src/display.c (hunk 2 above)
Comment (AdrianDC) [reply src/display.c:143]: Acknowledged, done in the next patchset.

File: src/display.c (hunk 3 above)
Comment (AdrianDC) [reply src/display.c:184]: Thanks!

File: src/display.c (hunk 1 above)
Comment (annacrombie) [reply src/display.c:158]: Ah yes, I see you are right.  Well, you should add the same `if (p->color) {` here then too.  I will just do it in a post-merge commit if there is nothing else.
